Adding support for ubuntu-touch i386 based images

diff --git a/live-build/auto/build b/live-build/auto/build
--- a/live-build/auto/build
+++ b/live-build/auto/build
@@ -409,9 +409,7 @@ if [ "$SUBARCH" = "ac100" ] || [ "$SUBARCH" = "nexus7" ]; then
 
 fi
 
-if [ "$PROJECT" = "ubuntu-touch" ] && [ "$ARCH" = "armhf" ]; then
-	touchsubarches="flo manta grouper mako generic"
-
+if [ "$PROJECT" = "ubuntu-touch" ]; then
 	sourceslist="chroot/etc/apt/sources.list"
 
 	lb chroot_proc install "$@"
@@ -437,20 +435,36 @@ if [ "$PROJECT" = "ubuntu-touch" ] && [ "$ARCH" = "armhf" ]; then
 	Chroot chroot "apt-get -y update"
 	Chroot chroot "apt-get -y install android"
 
-	for subarch in $touchsubarches; do
-		cp chroot/usr/share/android/product/*-preinstalled-system-armel+${subarch}.img\
-			 "${PREFIX}.system-armel+${subarch}.img"
-		cp chroot/usr/share/android/product/*-preinstalled-recovery-armel+${subarch}.img\
-			 "${PREFIX}.recovery-armel+${subarch}.img"
-		cp chroot/usr/share/android/product/*-preinstalled-boot-armhf+${subarch}.img\
-			 "${PREFIX}.boot-armhf+${subarch}.img"
-		# drop this following line once cdimage can handle -boot-*.img
-		cp "${PREFIX}.boot-armhf+${subarch}.img" "${PREFIX}.bootimg-${subarch}"
+	if [ "$ARCH" = "armhf" ]; then
+		touchsubarches="flo manta grouper mako generic"
+		for subarch in $touchsubarches; do
+			cp chroot/usr/share/android/product/*-preinstalled-system-armel+${subarch}.img\
+				"${PREFIX}.system-armel+${subarch}.img"
+			cp chroot/usr/share/android/product/*-preinstalled-recovery-armel+${subarch}.img\
+				"${PREFIX}.recovery-armel+${subarch}.img"
+			cp chroot/usr/share/android/product/*-preinstalled-boot-armhf+${subarch}.img\
+				"${PREFIX}.boot-armhf+${subarch}.img"
+			# drop this following line once cdimage can handle -boot-*.img
+			cp "${PREFIX}.boot-armhf+${subarch}.img" "${PREFIX}.bootimg-${subarch}"
 
-		# goldfish does not ship a .zip file, do not fail if it does not exist
-		cp chroot/usr/share/android/product/*-preinstalled-touch-armel+${subarch}.zip\
-			 "${PREFIX}.armel+${subarch}.zip" || true
-	done
+			# Android 4.4.2 based images don't ship a .zip file, do not fail if it does not exist
+			cp chroot/usr/share/android/product/*-preinstalled-touch-armel+${subarch}.zip\
+				"${PREFIX}.armel+${subarch}.zip" || true
+		done
+	fi
+	if [ "$ARCH" = "i386" ]; then
+		touchsubarches="generic_x86"
+		for subarch in $touchsubarches; do
+			cp chroot/usr/share/android/product/*-preinstalled-system-i386+${subarch}.img\
+				"${PREFIX}.system-i386+${subarch}.img"
+			cp chroot/usr/share/android/product/*-preinstalled-recovery-i386+${subarch}.img\
+				"${PREFIX}.recovery-i386+${subarch}.img"
+			cp chroot/usr/share/android/product/*-preinstalled-boot-i386+${subarch}.img\
+				"${PREFIX}.boot-i386+${subarch}.img"
+			# drop this following line once cdimage can handle -boot-*.img
+			cp "${PREFIX}.boot-i386+${subarch}.img" "${PREFIX}.bootimg-${subarch}"
+		done
+	fi
 
 	lb chroot_devpts remove "$@"
 	lb chroot_sysfs remove "$@"
